### ISSUE TITLE
Query Regarding r-phytools Dependency Conflict in Bioconda Build

### ISSUE THREAD

**Issue by AnupamGautam** [conda-forge/r-phytools-feedstock#17]
Dear Admin,  

I am trying to build a Conda package for the software *GenEra* (https://github.com/bioconda/bioconda-recipes/pull/51721), which uses **r-phytools**. The build works fine when I use `bioconda-utils build` on my server, but it encounters the following error on the Bioconda side.  

We are downloading **r-phytools** from the Bioconda channel, and the version being used is `0.6_99` ([Bioconda link](https://anaconda.org/bioconda/r-phytools)). However, the same package is also available in the Conda-Forge channel ([Conda-Forge link](https://anaconda.org/conda-forge/r-phytools)), but its versions start from `0.7_47`.  

Considering that Bioconda generally has higher priority than Conda-Forge, do you think the issue is related to this duplication or versioning? If so, is there a recommended way to resolve this conflict?  

Thank you for your help.  

Reloading output folder: ...working... done
23:10:21 BIOCONDA INFO (OUT) Solving environment (_test_env): ...working... failed
23:10:21 BIOCONDA INFO (OUT) WARNING: failed to get package records, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {MatchSpec("r-phytools==0.6_99=r40h6115d3f_1")}
23:10:21 BIOCONDA INFO (OUT) Encountered problems while solving:
23:10:21 BIOCONDA INFO (OUT)   - package r-phytools-0.6_99-r40h6115d3f_1 is excluded by strict repo priority
23:10:21 BIOCONDA INFO (OUT) 
23:10:23 BIOCONDA INFO (OUT) Reloading output folder: ...working... done
23:10:27 BIOCONDA INFO (OUT) Solving environment (_test_env): ...working... failed
23:10:29 BIOCONDA INFO (OUT) Reloading output folder: ...working... done
23:10:33 BIOCONDA INFO (OUT) Solving environment (_test_env): ...working... failed
23:10:35 BIOCONDA INFO (OUT) Reloading output folder: ...working... done
23:10:39 BIOCONDA INFO (OUT) Solving environment (_test_env): ...working... failed
23:10:39 BIOCONDA INFO (OUT) ERROR: Failed to get package records, max retries exceeded.
23:10:39 BIOCONDA INFO (OUT) 
23:10:39 BIOCONDA INFO (OUT) Leaving build/test directories:
23:10:39 BIOCONDA INFO (OUT)   Work:
23:10:39 BIOCONDA INFO (OUT)  /opt/conda/conda-bld/work
23:10:39 BIOCONDA INFO (OUT)   Test:
23:10:39 BIOCONDA INFO (OUT)  /opt/conda/conda-bld/test_tmp
23:10:39 BIOCONDA INFO (OUT) Leaving build/test environments:
23:10:39 BIOCONDA INFO (OUT)   Test:
23:10:39 BIOCONDA INFO (OUT) source activate  /opt/conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
23:10:39 BIOCONDA INFO (OUT)   Build:
23:10:39 BIOCONDA INFO (OUT) source activate  /opt/conda/conda-bld/_build_env
23:10:39 BIOCONDA INFO (OUT) 
23:10:39 BIOCONDA INFO (OUT) 
23:10:39 BIOCONDA INFO (OUT)     _actions = _install_actions(prefix, index, specs, subdir=subdir)
23:10:39 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1307, in install_actions
23:10:39 BIOCONDA INFO (OUT)     txn = solver.solve_for_transaction(prune=False, ignore_pinned=False)
23:10:39 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
23:10:39 BIOCONDA INFO (OUT)     unlink_precs, link_precs = self.solve_for_diff(
23:10:39 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 221, in solve_for_diff
23:10:39 BIOCONDA INFO (OUT)     final_precs = self.solve_final_state(
23:10:39 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 223, in solve_final_state
23:10:39 BIOCONDA INFO (OUT)     out_state = self._solving_loop(in_state, out_state, index)
23:10:39 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 303, in _solving_loop
23:10:39 BIOCONDA INFO (OUT)     solved = self._solve_attempt(in_state, out_state, index, attempt=attempt)
23:10:39 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 414, in _solve_attempt
23:10:39 BIOCONDA INFO (OUT)     new_conflicts = self._maybe_raise_for_problems(
23:10:39 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 712, in _maybe_raise_for_problems
23:10:39 BIOCONDA INFO (OUT)     self._maybe_raise_for_conda_build(
23:10:39 BIOCONDA INFO (OUT)   File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 805, in _maybe_raise_for_conda_build
23:10:39 BIOCONDA INFO (OUT)     raise exc
23:10:39 BIOCONDA INFO (OUT) conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("r-phytools==0.6_99=r40h6115d3f_1")}
23:10:39 BIOCONDA INFO (OUT) Encountered problems while solving:
23:10:39 BIOCONDA INFO (OUT)   - package r-phytools-0.6_99-r40h6115d3f_1 is excluded by strict repo priority
23:10:39 BIOCONDA INFO (OUT) 
23:10:46 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmpp7umkn45/build_script.bash:/opt/build_script.bash -v /opt/mambaforge/envs/bioconda/conda-bld:/opt/host-conda-bld -v /home/runner/work/bioconda-recipes/bioconda-recipes/recipes/genera:/opt/recipe -e LANG=C.UTF-8 -e HOST_USER_ID=1001 quay.io/bioconda/bioconda-utils-build-env-cos7:3.4.1 /bin/bash /opt/build_script.bash

23:10:46 BIOCONDA ERROR BUILD FAILED recipes/genera
23:10:46 BIOCONDA INFO (COMMAND) conda build purge

⠋ running (0:00:00.00)
                       
23:10:47 BIOCONDA ERROR BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
23:10:47 BIOCONDA ERROR BUILD SUMMARY: FAILED recipe recipes/genera
Error: Process completed with exit code 1.

Similar issue is here also https://github.com/bioconda/bioconda-recipes/pull/42327

Best regards,  
Anupam

**Comment by mfansler** [comment]
See https://github.com/bioconda/bioconda-recipes/pull/51721#issuecomment-2480831291. I.e., loosen the version requirements; otherwise, there needs to be a fix to Conda Forge or Bioconda.

**Comment by AnupamGautam** [comment]
Thank you.
